"""Excel versions of the claim documents, generated by the application."""

import base64
import json
import re
from datetime import date
from io import BytesIO

from openpyxl import Workbook
from openpyxl.drawing.image import Image
from openpyxl.styles import Alignment, Font, PatternFill

from backend.app.modules.claims.documents import (
    EXTRA_COLUMNS,
    INSTRUCTION_COLUMNS,
    TRACKER_COLUMNS,
)

EXCEL_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"


def _cell(sheet, row, column, value, key=""):
    cell = sheet.cell(row, column)
    if isinstance(value, (dict, list)):
        value = json.dumps(value, ensure_ascii=False)
    if isinstance(value, str):
        # Business text and invoice references must never become Excel formulas.
        cell.value = value
        cell.data_type = "s"
    else:
        cell.value = value
    if value and (key.endswith("_date") or key == "claim_date"):
        cell.value = date.fromisoformat(str(value))
        cell.number_format = "yyyy-mm-dd"
    elif isinstance(value, (float, int)) and not isinstance(value, bool):
        cell.number_format = "#,##0.00" if "amount" in key else "0.##"
    cell.alignment = Alignment(vertical="top", wrap_text=True)


def generate_excel(kind: str, data: dict) -> bytes:
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = {
        "technical": "Technical Report",
        "tracker": "Claim Tracker",
        "credit": "Instruction to Credit",
        "rejection": "Rejection Report",
    }[kind]
    if kind == "technical":
        sheet.append(["Field", "Value"])
        for key, value in data.items():
            if key == "photos":
                continue
            label = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", key).replace("_", " ")
            row = sheet.max_row + 1
            _cell(sheet, row, 1, label.capitalize())
            _cell(sheet, row, 2, value)
        sheet.column_dimensions["A"].width = 38
        sheet.column_dimensions["B"].width = 80
        if data.get("photos"):
            photos = workbook.create_sheet("Photos")
            photos.append(["Category", "Comment", "Photo"])
            photos.column_dimensions["A"].width = 28
            photos.column_dimensions["B"].width = 65
            photos.column_dimensions["C"].width = 45
            for row, photo in enumerate(data["photos"], start=2):
                _cell(photos, row, 1, photo.get("category"))
                _cell(photos, row, 2, photo.get("comment"))
                preview = photo.get("previewUrl", "")
                if preview.startswith("data:") and ";base64," in preview:
                    image = Image(BytesIO(base64.b64decode(preview.split(",", 1)[1])))
                    scale = min(300 / image.width, 220 / image.height, 1)
                    image.width *= scale
                    image.height *= scale
                    photos.add_image(image, f"C{row}")
                    photos.row_dimensions[row].height = 175
    else:
        columns = list(INSTRUCTION_COLUMNS if kind == "credit" else TRACKER_COLUMNS)
        columns.extend(EXTRA_COLUMNS)
        if kind == "credit":
            columns.extend(
                [
                    ("Issued to", "owner_name"),
                    ("Instruction notes", "instruction_notes"),
                ]
            )
        sheet.append([label for label, _ in columns])
        for column, (_, key) in enumerate(columns, start=1):
            _cell(sheet, 2, column, data.get(key), key)
            sheet.column_dimensions[sheet.cell(1, column).column_letter].width = 25
        sheet.row_dimensions[1].height = 48
        sheet.row_dimensions[2].height = 60
        sheet.auto_filter.ref = sheet.dimensions
    for page in workbook:
        page.freeze_panes = "A2"
        page.sheet_view.showGridLines = False
        for cell in page[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill("solid", fgColor="2F3398")
            cell.alignment = Alignment(vertical="center", wrap_text=True)
    result = BytesIO()
    workbook.save(result)
    return result.getvalue()
